name: Deploy Node Application

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t tej7k/node-js-app:latest .

      - name: Publish Image to Docker Hub
        run: docker push tej7k/node-js-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull tej7k/node-js-app:latest

      - name: Stop and Remove Old Container
        run: |
          if [ $(docker ps -q -f name=nodejs-app-container) ]; then
            docker rm -f nodejs-app-container
          fi

      - name: Run Docker Container
        run: docker run -d -p 4001:4001 --name nodejs-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' tej7k/node-js-app:latest
